"""add q_table

Revision ID: 914b10264808
Revises: 9c16f6bfafd2
Create Date: 2026-07-08 20:11:04.731261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '914b10264808'
down_revision: Union[str, Sequence[str], None] = '96c71f1bc6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_action_values', sa.JSON(), nullable=False),
    sa.Column('agent_stats', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activity_logs', sa.Column('target_type', sa.String(length=32), nullable=True))
    op.add_column('activity_logs', sa.Column('target_id', sa.String(length=64), nullable=True))
    op.alter_column('activity_logs', 'action',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.add_column('agent_sessions', sa.Column('status', sa.String(length=32), nullable=True))
    op.drop_index(op.f('ix_agent_sessions_session_key'), table_name='agent_sessions')
    op.add_column('alert_events', sa.Column('target_type', sa.String(length=32), nullable=False))
    op.add_column('alert_events', sa.Column('target_id', sa.String(length=64), nullable=False))
    op.add_column('alert_events', sa.Column('triggered_at', sa.DateTime(), nullable=False))
    op.alter_column('alert_events', 'severity',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               nullable=True)
    op.drop_index(op.f('ix_alert_events_agent_id'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_created_at'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.create_index(op.f('ix_alert_events_triggered_at'), 'alert_events', ['triggered_at'], unique=False)
    op.drop_constraint(op.f('alert_events_rule_id_fkey'), 'alert_events', type_='foreignkey')
    op.create_foreign_key(None, 'alert_events', 'alert_rules', ['rule_id'], ['id'], ondelete='SET NULL')
    op.drop_column('alert_events', 'created_at')
    op.drop_column('alert_events', 'details')
    op.drop_column('alert_events', 'acknowledged_by')
    op.drop_column('alert_events', 'agent_id')
    op.add_column('alert_rules', sa.Column('target_type', sa.String(length=32), nullable=False))
    op.add_column('alert_rules', sa.Column('target_id', sa.String(length=64), nullable=False))
    op.add_column('alert_rules', sa.Column('condition', sa.JSON(), nullable=False))
    op.add_column('alert_rules', sa.Column('threshold', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_alert_rules_agent_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_rule_type'), table_name='alert_rules')
    op.drop_column('alert_rules', 'agent_id')
    op.drop_column('alert_rules', 'severity')
    op.drop_column('alert_rules', 'condition_op')
    op.drop_column('alert_rules', 'condition_value')
    op.drop_column('alert_rules', 'condition_field')
    op.drop_column('alert_rules', 'rule_type')
    op.add_column('product_dependencies', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('product_dependencies', sa.Column('dependency_name', sa.String(length=200), nullable=False))
    op.add_column('product_dependencies', sa.Column('dependency_type', sa.String(length=32), nullable=False))
    op.add_column('product_dependencies', sa.Column('version', sa.String(length=64), nullable=True))
    op.add_column('product_dependencies', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_product_dependencies_from_product_id'), table_name='product_dependencies')
    op.drop_index(op.f('ix_product_dependencies_to_product_id'), table_name='product_dependencies')
    op.create_index(op.f('ix_product_dependencies_product_id'), 'product_dependencies', ['product_id'], unique=False)
    op.drop_constraint(op.f('product_dependencies_from_product_id_fkey'), 'product_dependencies', type_='foreignkey')
    op.drop_constraint(op.f('product_dependencies_to_product_id_fkey'), 'product_dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'product_dependencies', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product_dependencies', 'to_product_id')
    op.drop_column('product_dependencies', 'created_at')
    op.drop_column('product_dependencies', 'from_product_id')
    op.drop_column('product_dependencies', 'description')
    op.drop_column('product_dependencies', 'relation_type')
    op.add_column('products', sa.Column('product_id', sa.String(length=64), nullable=False))
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('products', 'owner',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    op.drop_column('products', 'type')
    op.drop_column('products', 'emoji')
    op.drop_column('products', 'positioning')
    op.drop_column('products', 'modules')
    op.drop_column('products', 'milestones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('milestones', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('modules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('positioning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('emoji', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.alter_column('products', 'owner',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('products', 'product_id')
    op.add_column('product_dependencies', sa.Column('relation_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('product_dependencies', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_dependencies', sa.Column('from_product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product_dependencies', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('product_dependencies', sa.Column('to_product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_dependencies', type_='foreignkey')
    op.create_foreign_key(op.f('product_dependencies_to_product_id_fkey'), 'product_dependencies', 'products', ['to_product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('product_dependencies_from_product_id_fkey'), 'product_dependencies', 'products', ['from_product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_dependencies_product_id'), table_name='product_dependencies')
    op.create_index(op.f('ix_product_dependencies_to_product_id'), 'product_dependencies', ['to_product_id'], unique=False)
    op.create_index(op.f('ix_product_dependencies_from_product_id'), 'product_dependencies', ['from_product_id'], unique=False)
    op.drop_column('product_dependencies', 'notes')
    op.drop_column('product_dependencies', 'version')
    op.drop_column('product_dependencies', 'dependency_type')
    op.drop_column('product_dependencies', 'dependency_name')
    op.drop_column('product_dependencies', 'product_id')
    op.add_column('alert_rules', sa.Column('rule_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('alert_rules', sa.Column('condition_field', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('alert_rules', sa.Column('condition_value', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('alert_rules', sa.Column('condition_op', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('alert_rules', sa.Column('severity', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('alert_rules', sa.Column('agent_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_alert_rules_rule_type'), 'alert_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_alert_rules_agent_id'), 'alert_rules', ['agent_id'], unique=False)
    op.drop_column('alert_rules', 'threshold')
    op.drop_column('alert_rules', 'condition')
    op.drop_column('alert_rules', 'target_id')
    op.drop_column('alert_rules', 'target_type')
    op.add_column('alert_events', sa.Column('agent_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('alert_events', sa.Column('acknowledged_by', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('alert_events', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('alert_events', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.create_foreign_key(op.f('alert_events_rule_id_fkey'), 'alert_events', 'alert_rules', ['rule_id'], ['id'])
    op.drop_index(op.f('ix_alert_events_triggered_at'), table_name='alert_events')
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alert_events_created_at'), 'alert_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_events_agent_id'), 'alert_events', ['agent_id'], unique=False)
    op.alter_column('alert_events', 'severity',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               nullable=False)
    op.drop_column('alert_events', 'triggered_at')
    op.drop_column('alert_events', 'target_id')
    op.drop_column('alert_events', 'target_type')
    op.create_index(op.f('ix_agent_sessions_session_key'), 'agent_sessions', ['session_key'], unique=False)
    op.drop_column('agent_sessions', 'status')
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('activity_logs', 'target_id')
    op.drop_column('activity_logs', 'target_type')
    op.drop_table('q_table')
    # ### end Alembic commands ###
